app/models.py
from app import db


class Site(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False, index=True)
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)
    elevation = db.Column(db.Float)
    region = db.Column(db.String(100))
    unitary_auth_area = db.Column(db.String(100))
    obs_source = db.Column(db.String(100))
    national_park = db.Column(db.String(100))
    observations = db.Column(db.Boolean, index=True)

    def __repr__(self):
        return '<Site: {} {}>'.format(self.id, self.name)

app/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from app.config import configs


db = SQLAlchemy()
migrate = Migrate()


from app.main.views import main as main_blueprint # noqa


def create_app():
    app = Flask(__name__)

    app.config.from_object(configs[app.env])

    db.init_app(app)
    migrate.init_app(app, db=db)

    app.register_blueprint(main_blueprint)

    return app

app/main/views.py
import os

import requests
from flask import Blueprint, abort, render_template, request

from app.datapoint_client.client import DatapointClient
from app.datapoint_client.errors import SiteError
from app.site_dao import dao_get_all_sites_with_observations, dao_get_observation_search_results, dao_get_site_by_id


main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/observations')
def all_site_observations():
    sites = dao_get_all_sites_with_observations()
    return render_template('observation_sites.html', sites=sites)


@main.route('/observations/<int:site_id>')
def site_observation(site_id):
    client = DatapointClient(os.getenv('DATAPOINT_API_KEY'))

    try:
        obs = client.get_all_obs_for_site(site_id)
    except SiteError:
        abort(404)
    except requests.exceptions.HTTPError as e:
        _abort_with_appropriate_error(e)

    site_name = dao_get_site_by_id(site_id).name

    return render_template('observation_single_site.html', obs=obs, site_name=site_name)


@main.route('/results')
def results():
    term = request.args.get('search-term')
    result = dao_get_observation_search_results(term)
    return render_template('results.html', term=result)


def _abort_with_appropriate_error(e):
    if e.response.status_code == 403:
        abort(403)
    elif e.response.status_code == 404:
        abort(404)
    else:
        abort(500)


@main.errorhandler(403)
def forbidden(error):
    return render_template('403.html'), 403


@main.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404


@main.errorhandler(500)
def internal_server_error(error):
    return render_template('500.html'), 500

app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>WxD</title>
  </head>
  <body>
    <div>
      <nav class="navbar navbar-expand-sm navbar-dark bg-info">
        <div class="container">
          <a class="navbar-brand" href="{{ url_for('main.index') }}">WxD</a>
          <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{{ url_for('main.index') }}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('main.all_site_observations') }}">Observations</a></li>
          </ul>
        </div>
      </nav>
      <br />
      <div class="container">
        {% block content %}{% endblock %}
      </div>
    </div>
  </body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div>
  <h1>WxD</h1>
</div>
<div>
  <p>
    This is the WxD homepage.
  </p>
  <p>
    You can view all weather observations for Heathrow <a href="{{ url_for('main.site_observation', site_id=3772) }}">here</a>.
  </p>
</div>
{% endblock %}

app/templates/observation_single_site.html
{% extends 'base.html' %}
{% block content %}
<div>
  <h1>Weather Observations for {{ site_name }}</h1>
</div>
<div>
  <table class="table table-striped table-responsive">
    <thead>
      <tr>
        <th scope="col">Date &amp; time</th>
        <th scope="col">Weather</th>
        <th scope="col">Temperature, &#x2103;</th>
        <th scope="col">Dew<br />point, &#x2103;</th>
        <th scope="col">Relative<br />humidity, %</th>
        <th scope="col">Wind, mph</th>
        <th scope="col">Wind<br />Gust, mph</th>
        <th scope="col">Pressure, hPa</th>
        <th scope="col">Visibility, m</th>
      </tr>
    </thead>
    <tbody>
    {% for date, content in obs.items() %}
      <tr>
        <th scope="row">{{ date }}</th>
        <td>{{ obs[date]['Weather Type'] }}</td>
        <td>{{ obs[date]['Temperature'] }}</td>
        <td>{{ obs[date]['Dew Point'] }}</td>
        <td>{{ obs[date]['Screen Relative Humidity'] }}</td>
        <td>{{ obs[date]['Wind Speed'] }} {{ obs[date]['Wind Direction'] }}</td>
        <td>{{ obs[date]['Wind Gust'] }}</td>
        <td>{{ obs[date]['Pressure'] }}<br />{{ obs[date]['Pressure Tendency'] }}</td>
        <td>{{ obs[date]['Visibility'] }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/observation_sites.html
{% extends 'base.html' %}
{% block content %}
<div>
  <h1>Weather Observation Sites</h1>
</div>
<div class="py-2">
  <form action="{{ url_for('main.results') }}">
    <div class="row">
      <div class="form-group col-sm-10">
        <label class="sr-only">Search for a site</label>
        <input class="form-control form-control-lg mx-2" name="search-term" type='text' placeholder="Search for a site by name"></input>
      </div>
      <div class="col-sm-2">
        <button type="submit" class="btn btn-lg btn-info">Search</button>
      </div>
    </div>
  </form>
</div>
<div>
  <p>Or select a site from the list below:</p>
  {% for site in sites %}
    <p class="site-links">
      <a href="{{ url_for('main.site_observation', site_id=site.id) }}">{{ site.name }}</a>
    </p>
  {% endfor %}
<div>
{% endblock %}

app/templates/results.html
{% extends 'base.html' %}
{% block content %}
<h1>Search Results</h1>
  {% if term %}
    {% for site in term %}
      <p class="site-links">
        <a href="{{ url_for('main.site_observation', site_id=site.id) }}">{{ site.name }}</a>
      </p>
    {% endfor %}
  {% else %}
    <p>We couldn't find that site.</p>
  {% endif %}
  <a class="btn btn-sm btn-outline-info" href="{{ url_for('main.all_site_observations') }}">Back</a>
{% endblock %}